export * from './beneficiario.repository';
export * from './captura.repository';
export * from './comunidad.repository';
export * from './persona-fisica.repository';
export * from './persona-moral.repository';
export * from './programa.repository';
export * from './solicitud.repository';
export * from './unidad.repository';
export * from './usuario.repository';
